working_directory: "/home/miha/Work/codes/ct-analyzer/"
results_directory: "/home/miha/Work/codes/ct-analyzer/test/results/"
injected_species: "k" # Lower case! Element abbreviation (e.g. Potassium -> "k", Sodium -> "na")
measured_charge_states: [3,4,5,6,7,8,9,10,11,12]

parse_raw_data:
  do: 0
  path_to_raw_data: "/home/miha/Work/codes/ct-analyzer/test/JA_2020-06-29/transient_data/"
  one_plus_naming_convention: "2020 06 29 - {} pulse 1+.txt"
  n_plus_naming_convention: "2020 06 29 - {} courant 1+.txt"
  filename_variables: [15 09 16,
15 04 09,
14 59 16,
14 52 47,
14 45 20,
14 39 01,
14 33 22,
14 10 00,
14 18 44,
14 23 20]
  conversion_factor: 0.0000011754 # Factor by which to multiply measured signal to convert it to units of A.
  separator: '\t' # Data separator in the raw data files. "\t" = tab; ","=comma; " "=space,...
  footer_length: 12 # If raw data has a footer, give number of rows in footer.
  header_length: 0 # If raw data has a header, give number of rows in header.
  rolling_average: 3 # Expressed as % of the data column length. Use value 0 to ignore.

optimize_abc:
  do: 0
  h: 1E-3 # RK4 method stepsize. Units of s.

optimize_nE:
  do: 1
  # Available rate coefficient evaluation methods:
  # - 'MB' -> interpolation functions based on a Maxwell-Boltzmann EED
  # For electron density limits, pass the tuple ('cutoff', FREQUENCY)
  # where FREQUENCY is the ion source microwave frequency in units of Hz.
  # The code will then calculate the cutoff frequency and use that
  # as the upper limit.
  rate_coefficient_method: "KAPPA-10"
  number_of_MC_iterations: 10
  number_of_density_iterations: 1000
  average_energy_limits: [10,10000] # Limits of the average energy of the EED [lower, higher]. Units of eV.
  electron_density_limits: [1e11, ['cutoff', 14.5E9]] # Limits of the electron density [lower, higher]. Units of 1/cm3.
  max_workers: 6 # Use -1 if you want to allow the use of all cpu's

plotting:
  do: 1
  heatmap_bins: 200 # Will create 200x200 grid for the heatmaps.
  sigma: 0
  confidence: 0.341
  average_energy_limits: [10,10000] # Set [lower, upper] limits of (n,E)-plotting.
  electron_density_limits: [1E11,['cutoff', 14.5E9]] # Use [0,0] for default limits.
  penalty_function_upper_limit: 1E-6
  plot_characteristic_minima: 1 
  advanced: # Set everything below this line to 0 by default.
    skip:   # If you want to skip plotting some values, set value to 1.
      confinement_time: 0
      charge_exchange_time: 0
      ionization_time: 0
    override_charge_states: 0
    charge_states: []